### ISSUE TITLE
Allow overriding rate limits for certain routes

### ISSUE THREAD

**Issue by hithroc** [aquarial/discord-haskell#16]
Recently I've encountered an issue that adding reaction route was very slow (1 reaction / 1s). I've checked the rate limits, and they were indeed lower than that at 1 reaction / 0.25s. Looking at what's going wrong I found out that rate limit reset time in `X-Ratelimit-Reset` is in seconds and if the rate limit is lower than a second it is rounded up to the closest second.

Apparently this issue is "won't fix": https://github.com/discordapp/discord-api-docs/issues/182

I do not propose to hardcode the rate limits into the library for this particular route (even though that's many libraries do as far as I'm aware), but some way to manually override them would be nice.

**Comment by aquarial** [comment]
I think it's okay to hardcode the ratelimit for reaction rate for this endpoint. 

Since discord is not going to change the ratelimit for backwards compatibility and other libraries have already hardcoded it, they are going to keep this ratelimit. Therefore it is entirely safe to hardcode it. 

Another thing is that the Rest loop is running in another thread. I could add a `Request` sub-type that is `ConfigRequest` that allows changing settings, but that will complicate [writeRestCall](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Rest.hs#L40) a significant amount. 

While I'm usually against hardcoding stuff, I think it's a good tradeoff here, compared to other options.

**Comment by aquarial** [comment]
Fixed in https://github.com/aquarial/discord-haskell/commit/81fc96e91eda57a62c55da38973e4a65b0092c18. I've hardcoded CreateReaction to 0.25s. Also released v0.8.2 with this change. Thanks for doing the research on the ratelimits.

**Comment by hithroc** [comment]
Amazing, thanks!
