### ISSUE TITLE
Regarding `MessageUpdate`

### ISSUE THREAD

**Issue by mniip** [aquarial/discord-haskell#20]
As per the changelog:

> MessageUpdate does not contain a full Message object, just ChannelId MessageId

How then is one supposed to get the contents of the updated message?

**Comment by aquarial** [comment]
Send a [GetChannelMessage](https://discordapp.com/developers/docs/resources/channel#get-channel-message) request with the ChannelId MessageId pair.

```haskell
~> :info GetChannelMessage
type role ChannelRequest nominal
data ChannelRequest a where
  ...
  GetChannelMessage :: (ChannelId, MessageId) -> ChannelRequest Message
  ...
        -- Defined at ~/programming/haskell/discord-haskell/src/Discord/Rest/Channel.hs:47:3
```

I removed the full `Message` from `MessageUpdate` because of Issue https://github.com/aquarial/discord-haskell/issues/10. `MessageUpdate` is only guaranteed to send ChannelId and Messageid. In retrospect, I could have seamlessly done the rest request behind the scenes. It would add complexity to library (what to do if the rest request fails?), but the point of a library is to be complicated and expose a simpler interface. For now this is the way it is.
