### ISSUE TITLE
ModifyGuildRolePositions results in 400 Bad Request 

### ISSUE THREAD

**Issue by michalrus** [aquarial/discord-haskell#24]
I’m calling `ModifyGuildRolePositions`, and getting this back:

```
Your code threw an exception:

GuildRequest [Role]: RestCallErrorCode 400 "BAD REQUEST" "{\"_misc\": [\"Only dictionaries may be used in a DictType\"]}"
```

**Comment by michalrus** [comment]
`Only dictionaries may be used in a DictType` would suggest some JSON formatting error in request body, maybe? But I don’t know how to easily check what’s being sent exactly, since it’s over TLS.

**Comment by aquarial** [comment]
Fixed with https://github.com/aquarial/discord-haskell/commit/85dbaa8ce8ff481d3eaf2989484ca29e4ee546e7, pushed to version 1.1.1

A tricky error to debug.

`ModifyGuildRolePositions` was running `POST /guilds/{guild.id}/roles`, which [goes to CreateGuildRole](https://discordapp.com/developers/docs/resources/guild#create-guild-role)

It should have gone to `PATCH /guilds/{guild.id}/roles`, for [the correct url](https://discordapp.com/developers/docs/resources/guild#modify-guild-role-positions)

The error message is because we send a `Array` instead of an Object.  `ModifyGuildRolePositions` expects an array, but `CreateGuildRole` expects a `Object`. The real error was that the request was going to the wrong receiver.

**Comment by michalrus** [comment]
Wow, thank you for such a quick reaction! :revolving_hearts:

**Comment by michalrus** [comment]
Hm, somewhat related — do you maybe know why I would be getting `Missing permissions` for this endpoint (`ModifyGuildRolePositions`), if my bot has:
* ADD_REACTIONS     0x00000040
* SEND_MESSAGES	0x00000800
* VIEW_CHANNEL	0x00000400
* MANAGE_ROLES \*	0x10000000

**Comment by michalrus** [comment]
Oh, it’s because you can’t manage roles higher than yours!

Thanks again for the quick fix. =)
