### ISSUE TITLE
Edit message returning rest error

### ISSUE THREAD

**Issue by annogram** [aquarial/discord-haskell#38]
Running this simple line on a message returns a rest error

```haskell
res <- restCall h $ R.EditMessage (messageChannel m, messageId m) "changed" Nothing
    print res
```

```
Left (RestCallErrorCode 400 "Bad Request" "{\"_misc\": [\"Expected \\\"Content-Type\\\" header to be one of {'application/json'}.\"]}")
```

**Comment by aquarial** [comment]
Interesting. This bug started when I reworked the Embed structs. Embeds can upload images to use in them instead of using urls.

[CreateMessage](https://discordapp.com/developers/docs/resources/channel#create-message) takes json or form-data, because form-data can upload files alongside the embed.

[EditMessage](https://discordapp.com/developers/docs/resources/channel#edit-message) only takes json, so the embed uploaded can’t upload files!

**Comment by aquarial** [comment]
The question is: how to handle cases where EditMessage embed wants to send `CreateEmbedImageUpload` with a **different** image then CreateMessageEmbed put.

Can't upload the image bc json, Erroring out before sending is annoying because we don't know if it's the same image, Silently failing is annoying.

**Comment by annogram** [comment]
The api for edit mentions that it takes an extra field for embed. Does it expect that data to be serialized in a certain way?

**Comment by aquarial** [comment]
It expects JSON format. `EditMessage` takes `CreateEmbed`, and uses `createEmbed :: CreateEmbed -> Embed` to get `Embed`, which implements `ToJSON`.

I've got a school project due tonight that I should be working on, so I'll be more active tomorrow...

**Comment by aquarial** [comment]
Fixed with https://github.com/aquarial/discord-haskell/commit/5e726917d46449791f0e647242c9c282d0d63b32

`reqBodyMultipart` can upload files, `ReqBodyJson` can't.

Since the `EditMessage` requires a json body (can't take multipart-data), we can't upload files alongside the Embed in an `EditMessage`. 

Using `CreateEmbedImage` to upload a new file in `EditMessage` will fail silently, but I think it's the best tradeoff I can get.

**Comment by annogram** [comment]
Pulled the latest version of this from hackage and tried to install it to my project but getting errors with ping-pong executable now:

```
discord-haskell> [25 of 25] Compiling Discord.Types
discord-haskell> Preprocessing executable 'ping-pong' for discord-haskell-1.5.1..
discord-haskell> Building executable 'ping-pong' for discord-haskell-1.5.1..
discord-haskell> [1 of 1] Compiling Main
discord-haskell> 
discord-haskell> /tmp/stack897/discord-haskell-1.5.1/examples/ping-pong.hs:7:1: error:
discord-haskell>     Could not load module ‘Data.ByteString’
discord-haskell>     It is a member of the hidden package ‘bytestring-0.10.10.0’.
discord-haskell>     Perhaps you need to add ‘bytestring’ to the build-depends in your .cabal file.
discord-haskell>     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
discord-haskell>   |
discord-haskell> 7 | import qualified Data.ByteString as B
discord-haskell>   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discord-haskell> 
```

**Comment by aquarial** [comment]
Ah, I made a small mistake pushing the 1.5.1 version.

I made some changes to examples/pingpong.hs, but didn't commit them. Then I ran `stack upload .` and it packaged the modified pingpong. I'll push 1.5.2 soon

**Comment by aquarial** [comment]
Alright, 1.5.2 fixed that

**Comment by annogram** [comment]
Awesome dude! works now
