### ISSUE TITLE
Crash on startup due to null parent_id on channel

### ISSUE THREAD

**Issue by dyerw** [aquarial/discord-haskell#55]
I'm getting the following error when I try to start my bot up:

```
GatewayExceptionEventParseError "Error in $: Error in $.channels[0]['parent_id']: mzero" "Normal event loop"
```

in the logged JSON that fails to parse this is element 0 in channels

```
      {
        "type": 0,
        "topic": null,
        "rate_limit_per_user": 0,
        "position": 0,
        "permission_overwrites": [],
        "parent_id": null,
        "nsfw": false,
        "name": "general",
        "last_pin_timestamp": "2020-01-01T00:18:32.457000+00:00",
        "last_message_id": "745156032938115082",
        "id": "138467465867821057"
      }
```

**Comment by aquarial** [comment]
Fixed with 1.8.0

I knew [channel type -> parent_id](https://discord.com/developers/docs/resources/channel#channel-object-channel-structure) could be null, but for some reason I thought it would always be non-null for Text channels (type 0). 

Weird that it never crashed before this? Maybe something changed...

Anyway, new fix pushed

**Comment by dyerw** [comment]
Thanks for the quick response! I'll test it later today and close if working.

**Comment by dyerw** [comment]
Finally got around to testing the update and everything looks great!
